### PR TITLE
Litex dt binding json schema conversions

### PR DESCRIPTION
**Pull request by geertu**
Cc @rw1nkler

### CODE REVIEW

**Comment by gsomlo** [comment]
@geertu -- thanks, I applied the i2c patch. Can you redo the gpio one to also handle the changes in 03dfe4de8209d ?

**Comment by geertu** [comment]
@gsomlo Sure, will take care of it.

**Comment by geertu** [comment]
> @geertu -- thanks, I applied the i2c patch. Can you redo the gpio one to also handle the changes in [03dfe4d](https://github.com/litex-hub/linux/commit/03dfe4de8209d4bb8d54bfd20f6d9d7f34a8d3f0) ?

@gsomlo Done.

**Comment by gsomlo** [comment]
Applied, thanks! At the moment, it should show up here: https://github.com/litex-hub/linux/commit/b6c64a8c4e292aea7077740b7e47497d37356ed7 (but might get re-numbered after further rebasing).

**Pull request closed without merging**
